class DeleteError(Exception):
    pass

class NotFoundError(Exception):
    pass
